package io.github.rhysbeynon.spacer.client.Interface;

import org.lwjgl.glfw.GLFW;

import java.util.HashMap;
import java.util.Map;

public class KeyNames {
    public static Map<Integer, String> getKeyNames() {
        Map<Integer, String> keyNames = new HashMap<>();
        keyNames.put(GLFW.GLFW_KEY_A, "A");
        keyNames.put(GLFW.GLFW_KEY_B, "B");
        keyNames.put(GLFW.GLFW_KEY_C, "C");
        keyNames.put(GLFW.GLFW_KEY_D, "D");
        keyNames.put(GLFW.GLFW_KEY_E, "E");
        keyNames.put(GLFW.GLFW_KEY_F, "F");
        keyNames.put(GLFW.GLFW_KEY_G, "G");
        keyNames.put(GLFW.GLFW_KEY_H, "H");
        keyNames.put(GLFW.GLFW_KEY_I, "I");
        keyNames.put(GLFW.GLFW_KEY_J, "J");
        keyNames.put(GLFW.GLFW_KEY_K, "K");
        keyNames.put(GLFW.GLFW_KEY_L, "L");
        keyNames.put(GLFW.GLFW_KEY_M, "M");
        keyNames.put(GLFW.GLFW_KEY_N, "N");
        keyNames.put(GLFW.GLFW_KEY_O, "O");
        keyNames.put(GLFW.GLFW_KEY_P, "P");
        keyNames.put(GLFW.GLFW_KEY_Q, "Q");
        keyNames.put(GLFW.GLFW_KEY_R, "R");
        keyNames.put(GLFW.GLFW_KEY_S, "S");
        keyNames.put(GLFW.GLFW_KEY_T, "T");
        keyNames.put(GLFW.GLFW_KEY_U, "U");
        keyNames.put(GLFW.GLFW_KEY_V, "V");
        keyNames.put(GLFW.GLFW_KEY_W, "W");
        keyNames.put(GLFW.GLFW_KEY_X, "X");
        keyNames.put(GLFW.GLFW_KEY_Y, "Y");
        keyNames.put(GLFW.GLFW_KEY_Z, "Z");
        keyNames.put(GLFW.GLFW_KEY_0, "0");
        keyNames.put(GLFW.GLFW_KEY_1, "1");
        keyNames.put(GLFW.GLFW_KEY_2, "2");
        keyNames.put(GLFW.GLFW_KEY_3, "3");
        keyNames.put(GLFW.GLFW_KEY_4, "4");
        keyNames.put(GLFW.GLFW_KEY_5, "5");
        keyNames.put(GLFW.GLFW_KEY_6, "6");
        keyNames.put(GLFW.GLFW_KEY_7, "7");
        keyNames.put(GLFW.GLFW_KEY_8, "8");
        keyNames.put(GLFW.GLFW_KEY_9, "9");
        keyNames.put(GLFW.GLFW_KEY_MINUS, "-");
        keyNames.put(GLFW.GLFW_KEY_EQUAL, "=");
        keyNames.put(GLFW.GLFW_KEY_BACKSPACE, "Backspace");
        keyNames.put(GLFW.GLFW_KEY_LEFT_SHIFT, "Left Shift");
        keyNames.put(GLFW.GLFW_KEY_RIGHT_SHIFT, "Right Shift");
        keyNames.put(GLFW.GLFW_KEY_LEFT_CONTROL, "Left Control");
        keyNames.put(GLFW.GLFW_KEY_RIGHT_CONTROL, "Right Control");
        keyNames.put(GLFW.GLFW_KEY_LEFT_ALT, "Left Alt");
        keyNames.put(GLFW.GLFW_KEY_RIGHT_ALT, "Right Alt");
        keyNames.put(GLFW.GLFW_KEY_SPACE, "Space");
        keyNames.put(GLFW.GLFW_KEY_ESCAPE, "Escape");
        keyNames.put(GLFW.GLFW_KEY_ENTER, "Enter");
        keyNames.put(GLFW.GLFW_KEY_TAB, "Tab");
        keyNames.put(GLFW.GLFW_KEY_DELETE, "Delete");
        keyNames.put(GLFW.GLFW_KEY_LEFT, "Left");
        keyNames.put(GLFW.GLFW_KEY_RIGHT, "Right");
        keyNames.put(GLFW.GLFW_KEY_UP, "Up");
        keyNames.put(GLFW.GLFW_KEY_DOWN, "Down");
        keyNames.put(GLFW.GLFW_KEY_F1, "F1");
        keyNames.put(GLFW.GLFW_KEY_F2, "F2");
        keyNames.put(GLFW.GLFW_KEY_F3, "F3");
        keyNames.put(GLFW.GLFW_KEY_F4, "F4");
        keyNames.put(GLFW.GLFW_KEY_F5, "F5");
        keyNames.put(GLFW.GLFW_KEY_F6, "F6");
        keyNames.put(GLFW.GLFW_KEY_F7, "F7");
        keyNames.put(GLFW.GLFW_KEY_F8, "F8");
        keyNames.put(GLFW.GLFW_KEY_F9, "F9");
        keyNames.put(GLFW.GLFW_KEY_F10, "F10");
        keyNames.put(GLFW.GLFW_KEY_F11, "F11");
        keyNames.put(GLFW.GLFW_KEY_F12, "F12");
        keyNames.put(GLFW.GLFW_KEY_LEFT_SUPER, "Left Super");
        keyNames.put(GLFW.GLFW_KEY_RIGHT_SUPER, "Right Super");
        keyNames.put(GLFW.GLFW_KEY_LEFT_BRACKET, "[");
        keyNames.put(GLFW.GLFW_KEY_RIGHT_BRACKET, "]");
        keyNames.put(GLFW.GLFW_KEY_BACKSLASH, "\\");
        keyNames.put(GLFW.GLFW_KEY_SEMICOLON, ";");
        keyNames.put(GLFW.GLFW_KEY_APOSTROPHE, "'");
        keyNames.put(GLFW.GLFW_KEY_COMMA, ",");
        keyNames.put(GLFW.GLFW_KEY_PERIOD, ".");
        keyNames.put(GLFW.GLFW_KEY_SLASH, "/");
        keyNames.put(GLFW.GLFW_KEY_GRAVE_ACCENT, "`");
        keyNames.put(GLFW.GLFW_KEY_WORLD_1, "World 1");
        keyNames.put(GLFW.GLFW_KEY_WORLD_2, "World 2");
        keyNames.put(GLFW.GLFW_KEY_INSERT, "Insert");
        keyNames.put(GLFW.GLFW_KEY_PAGE_UP, "Page Up");
        keyNames.put(GLFW.GLFW_KEY_PAGE_DOWN, "Page Down");
        keyNames.put(GLFW.GLFW_KEY_HOME, "Home");
        keyNames.put(GLFW.GLFW_KEY_END, "End");
        keyNames.put(GLFW.GLFW_KEY_CAPS_LOCK, "Caps Lock");
        keyNames.put(GLFW.GLFW_KEY_SCROLL_LOCK, "Scroll Lock");
        keyNames.put(GLFW.GLFW_KEY_NUM_LOCK, "Num Lock");
        keyNames.put(GLFW.GLFW_KEY_PRINT_SCREEN, "Print Screen");
        keyNames.put(GLFW.GLFW_KEY_PAUSE, "Pause");
        return keyNames;
    }
}
